### ISSUE TITLE
One sensor

### ISSUE THREAD

**Issue by GlebDen** [SeBassTian23/ESP32-WeatherDisplay#1]
Hello!
Very interesting project! 
I just want to ask why don't you using one pcb with all 3 sensors like CJMCU-8128 (board with CCS811, BMP280 and SI702x)?
Thank you.

p.s. It's not an issue but I don't understand how to label this message as 'enhancement' for example :(

**Comment by SeBassTian23** [comment]
Hi @GlebDen,

I'm glad you like the project! That is a very interesting breakout board. The reason I used three breakout boards is very simple. I just had them lying around and wanted to use them before buying something new. I also added the label enhancement 😄 .

Best
